Sprint 6 solution
Kravchi88/java-kanban pull request #1
Opened 2024-04-28 00:30 UTC by Kravchi88

Здравствуйте. Пара вещей, о которых хочу сказать:
1- Только сейчас понял, что названия коммитов слишком длинные. В следующий раз будут короче.
2- Изначально InMemoryHistoryManager был параметризованным классом, можно посмотреть в первом коммите. потом я подумал, что это лишние действия и убрал параметр.

2024-04-28 17:06 UTC, kalitva commented
> Здравствуйте. Пара вещей, о которых хочу сказать: 1- Только сейчас понял, что названия коммитов слишком длинные. В следующий раз будут короче.

Почитай вот например https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/, или погугли самостоятельно по тегу commit convention

> 2- Изначально InMemoryHistoryManager был параметризованным классом, можно посмотреть в первом коммите. потом я подумал, что это лишние действия и убрал параметр. 

Правильно

> 3- Что не так с аннотацией @NotNull? (последний коммит, с этой аннотацией не проходили проверки на гитхабе)

С аннотацией думаю все ок, а вот пайплайн на гитхабе может барагозить. Как он устроен не знаю, можешь поспрашивать наставника

2024-04-28 17:17 UTC, kalitva requested changes

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/HistoryManager.java
>      void addToHistory(Task task);
`addToHistory --> add`

И так понятно куда (название интерфейса) и что (название параметра) мы добавляем

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/HistoryManager.java
> +    void removeFromHistory(int id);
То же самое

```java
void remove(int taskId);
```

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryHistoryManager.java
> +    static class Node<E> {
1. private static
2. И убери параметризацию, этот класс только для внутреннего пользования

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryHistoryManager.java
> +        E instance;
`E instance --> Task task;`

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryHistoryManager.java
> +        public Node(Node<E> prev, Node<E> next, E instance) {
Оставь только параметр задачи, будет очевиднее что куда присваивается

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryTaskManager.java
> +    public HistoryManager getHistoryManager() {
Удали этот геттер

2024-04-28 17:17 UTC, kalitva commented on test/ru/yandex/practicum/manager/HistoryManagerTest.java
> +        task2.setId(2);
Вынеси создание таска в приватный метод чтобы создават таски в одно выражение:

```java
Task task1 = task(1);
```

2024-04-28 17:17 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryTaskManager.java
> +        }
```java
tasks.keySet().forEach(historyManager::removeFromHistory);
```

Как насчет использовать forEach?

2024-04-28 17:42 UTC, Kravchi88 commented on src/ru/yandex/practicum/manager/InMemoryTaskManager.java
> +    public HistoryManager getHistoryManager() {
Он нужен, чтобы в main() вызвать менеджера истории, который находится именно внутри менеджера задач. Если я удалю этот геттер, мне придётся делать само поле менеджера публичным. Иначе я просто не смогу проверить пользовательский сценарий (дополнительный пункт тз).

2024-04-28 18:20 UTC, Kravchi88 commented on src/ru/yandex/practicum/manager/InMemoryTaskManager.java
> +        }
Я исправил, но я не знаю, что это такое. Особенно вопросы вызывает двойное двоеточие. Можете, пожалуйста, скинуть ссылку на документацию, если не сложно? Я искал в документации интерфейсов Set и Iterable и ничего там не нашёл.

2024-04-29 19:39 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryTaskManager.java
> +    public HistoryManager getHistoryManager() {
Нельзя ослаблять инкапсуляцию только для того, чтобы что-то протестить в main. Пришли мне в личку, какой конкретно пункт тз имеешь ввиду

2024-04-29 19:47 UTC, kalitva commented on src/ru/yandex/practicum/manager/InMemoryTaskManager.java
> +        }
https://habr.com/ru/articles/512730/ - лямбды
https://www.baeldung.com/java-method-references - метод референс (то, что с двоеточием)

Если лямбды еще не знаешь, то можешь отложить, будете проходить дальше

2024-04-29 19:48 UTC, kalitva approved these changes

2024-04-29 19:48 UTC, kalitva commented on test/ru/yandex/practicum/manager/HistoryManagerTest.java
> +    Task task(int id) {
private

2024-04-29 23:49 UTC, merged